{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "158df5a6-3c27-4384-a3d7-0c5e85d58bb7",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T14:59:44.804424Z",
     "iopub.status.busy": "2025-01-16T14:59:44.804124Z",
     "iopub.status.idle": "2025-01-16T14:59:44.810531Z",
     "shell.execute_reply": "2025-01-16T14:59:44.809858Z",
     "shell.execute_reply.started": "2025-01-16T14:59:44.804403Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import subprocess\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4431dd8a-db72-4d8c-96c7-3f1c9e548a0f",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T14:45:39.383453Z",
     "iopub.status.busy": "2025-01-16T14:45:39.383044Z",
     "iopub.status.idle": "2025-01-16T14:45:39.389170Z",
     "shell.execute_reply": "2025-01-16T14:45:39.388483Z",
     "shell.execute_reply.started": "2025-01-16T14:45:39.383429Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-16 09:45:39.474 EST [398405] LOG:  starting PostgreSQL 17.2 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (Anaconda gcc) 11.2.0, 64-bit\n",
      "2025-01-16 09:45:39.474 EST [398405] LOG:  listening on IPv6 address \"::1\", port 5433\n",
      "2025-01-16 09:45:39.474 EST [398405] LOG:  listening on IPv4 address \"127.0.0.1\", port 5433\n",
      "2025-01-16 09:45:39.530 EST [398405] LOG:  listening on Unix socket \"/tmp/.s.PGSQL.5433\"\n",
      "2025-01-16 09:45:39.645 EST [398409] LOG:  database system was shut down at 2025-01-16 09:44:49 EST\n",
      "2025-01-16 09:45:39.796 EST [398405] LOG:  database system is ready to accept connections\n"
     ]
    }
   ],
   "source": [
    "#start the database\n",
    "process = subprocess.Popen([\"postgres\", \"-D\", \"/home/mcn26/palmer_scratch/db\", \"-p\", \"5433\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fa396994-2668-4bbf-88a6-390aaee17490",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T14:59:46.695126Z",
     "iopub.status.busy": "2025-01-16T14:59:46.694743Z",
     "iopub.status.idle": "2025-01-16T14:59:46.702333Z",
     "shell.execute_reply": "2025-01-16T14:59:46.701658Z",
     "shell.execute_reply.started": "2025-01-16T14:59:46.695103Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The sql extension is already loaded. To reload it, use:\n",
      "  %reload_ext sql\n"
     ]
    }
   ],
   "source": [
    "# Load the SQL extension\n",
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "645f948f-b905-4a42-8c42-6027ae0b2543",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-15T22:50:40.918588Z",
     "iopub.status.busy": "2025-01-15T22:50:40.918101Z",
     "iopub.status.idle": "2025-01-15T22:50:45.925824Z",
     "shell.execute_reply": "2025-01-15T22:50:45.925385Z",
     "shell.execute_reply.started": "2025-01-15T22:50:40.918567Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import time\n",
    "print(\"[+] Waiting 1 min for the server to start before attempting a connection.\")\n",
    "time.sleep(60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9e75f6e0-e977-4f6c-a38e-c8195653596e",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T14:45:43.098462Z",
     "iopub.status.busy": "2025-01-16T14:45:43.098071Z",
     "iopub.status.idle": "2025-01-16T14:45:43.329153Z",
     "shell.execute_reply": "2025-01-16T14:45:43.328491Z",
     "shell.execute_reply.started": "2025-01-16T14:45:43.098436Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "%%sql\n",
    "postgresql://mr_root:password@localhost:5433/scratch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "e64e323f-e0a8-4c57-a394-e6f18696ea10",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T15:20:49.324453Z",
     "iopub.status.busy": "2025-01-16T15:20:49.323840Z",
     "iopub.status.idle": "2025-01-16T15:20:49.329616Z",
     "shell.execute_reply": "2025-01-16T15:20:49.329190Z",
     "shell.execute_reply.started": "2025-01-16T15:20:49.324425Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3302, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 621, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/psycopg2/__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"r814u09n11\" (10.178.138.27), port 5433 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sql/connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sql/connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3278, in connect\n",
      "    return self._connection_cls(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 148, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 2442, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3302, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 621, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/gpfs/gibbs/project/reilly/mcn26/conda_envs/mcn_varef/lib/python3.10/site-packages/psycopg2/__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"r814u09n11\" (10.178.138.27), port 5433 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['postgresql://mr_root:***@localhost:5433/scratch'])\n"
     ]
    }
   ],
   "source": [
    "##%%sql\n",
    "##postgresql://mr_root:password@r814u09n11:5433/scratch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7c91e4d9-b504-4ee9-9f0d-b64ec60796b3",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T14:45:46.358880Z",
     "iopub.status.busy": "2025-01-16T14:45:46.358503Z",
     "iopub.status.idle": "2025-01-16T14:45:46.365493Z",
     "shell.execute_reply": "2025-01-16T14:45:46.364829Z",
     "shell.execute_reply.started": "2025-01-16T14:45:46.358857Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "#dealing with a weird bug\n",
    "%config SqlMagic.style = '_DEPRECATED_DEFAULT'"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "01e03b96-c092-483e-9369-32957ff55da3",
   "metadata": {},
   "source": [
    "Let's examine some lines of the gnomad data:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "fd54ccc9-3557-48b8-adac-31444715a4e4",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-15T22:38:54.293758Z",
     "iopub.status.busy": "2025-01-15T22:38:54.293266Z",
     "iopub.status.idle": "2025-01-15T22:38:54.313350Z",
     "shell.execute_reply": "2025-01-15T22:38:54.312983Z",
     "shell.execute_reply.started": "2025-01-15T22:38:54.293728Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n",
      "chr10\t10265\t.\tC\tT\t.\t.\tK562__ref=0.06947866;HepG2__ref=-0.1994611;SKNSH__ref=-0.60886025;K562__alt=0.07767675;HepG2__alt=-0.2021158;SKNSH__alt=-0.62348086;K562__skew=0.0081980955;HepG2__skew=-0.0026547052;SKNSH__skew=-0.01462063\n",
      "\n"
     ]
    }
   ],
   "source": [
    "command = \"zcat /gpfs/gibbs/pi/reilly/VariantEffects/scripts/noon_scripts/0.merge/out/ | grep -v ^## | head -n2\"\n",
    "result = subprocess.run(command, shell=True, capture_output=True, text=True)\n",
    "\n",
    "# Print the output\n",
    "print(result.stdout)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "79f7c69c-2193-42a3-abcf-c7a56d819ed8",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-15T22:37:24.596246Z",
     "iopub.status.busy": "2025-01-15T22:37:24.595973Z",
     "iopub.status.idle": "2025-01-15T22:37:41.390417Z",
     "shell.execute_reply": "2025-01-15T22:37:41.390042Z",
     "shell.execute_reply.started": "2025-01-15T22:37:24.596227Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * postgresql://mr_root:***@localhost:5433/scratch\n",
      "Done.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%%sql\n",
    "DROP TABLE malin_gnomad"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "a21ca7df-caef-4fc9-91e4-5ac6427b6620",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-06T22:24:20.033012Z",
     "iopub.status.busy": "2025-01-06T22:24:20.032563Z",
     "iopub.status.idle": "2025-01-06T22:24:20.114586Z",
     "shell.execute_reply": "2025-01-06T22:24:20.114248Z",
     "shell.execute_reply.started": "2025-01-06T22:24:20.032987Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * postgresql://mr_root:***@localhost:5433/scratch\n",
      "Done.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[]"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%%sql\n",
    "CREATE TABLE malin_gnomad (\n",
    "    chromosome_id TEXT,\n",
    "    pos INT,\n",
    "    id TEXT,\n",
    "    ref TEXT,\n",
    "    alt TEXT,\n",
    "    info TEXT\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "17279b31-84a4-4ff6-bcb3-e4d8f2a32f0f",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-06T22:31:11.636256Z",
     "iopub.status.busy": "2025-01-06T22:31:11.635658Z",
     "iopub.status.idle": "2025-01-06T22:37:44.388778Z",
     "shell.execute_reply": "2025-01-06T22:37:44.388412Z",
     "shell.execute_reply.started": "2025-01-06T22:31:11.636232Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * postgresql://mr_root:***@localhost:5433/scratch\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-06 17:31:51.469 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:32:27.398 EST [2882019] LOG:  checkpoint complete: wrote 22 buffers (0.1%); 0 WAL file(s) added, 0 removed, 33 recycled; write=34.064 s, sync=0.114 s, total=35.930 s; sync files=3, longest=0.082 s, average=0.038 s; distance=535133 kB, estimate=535133 kB; lsn=2/EF8F328, redo lsn=1/F1136AA8\n",
      "2025-01-06 17:32:27.828 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:32:51.302 EST [2882019] LOG:  checkpoint complete: wrote 27 buffers (0.2%); 0 WAL file(s) added, 0 removed, 33 recycled; write=21.950 s, sync=0.021 s, total=23.474 s; sync files=2, longest=0.014 s, average=0.011 s; distance=541654 kB, estimate=541654 kB; lsn=2/2FE22B38, redo lsn=2/1222C348\n",
      "2025-01-06 17:32:52.094 EST [2882019] LOG:  checkpoints are occurring too frequently (25 seconds apart)\n",
      "2025-01-06 17:32:52.094 EST [2882019] HINT:  Consider increasing the configuration parameter \"max_wal_size\".\n",
      "2025-01-06 17:32:52.096 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:33:21.943 EST [2882019] LOG:  checkpoint complete: wrote 21 buffers (0.1%); 0 WAL file(s) added, 0 removed, 33 recycled; write=28.356 s, sync=0.101 s, total=29.849 s; sync files=3, longest=0.063 s, average=0.034 s; distance=539151 kB, estimate=541403 kB; lsn=2/50E40F68, redo lsn=2/330B0270\n",
      "2025-01-06 17:33:24.677 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:34:04.089 EST [2882019] LOG:  checkpoint complete: wrote 27 buffers (0.2%); 0 WAL file(s) added, 0 removed, 33 recycled; write=37.768 s, sync=0.032 s, total=39.412 s; sync files=2, longest=0.018 s, average=0.016 s; distance=540575 kB, estimate=541321 kB; lsn=2/71C691F8, redo lsn=2/54097EE8\n",
      "2025-01-06 17:34:06.400 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:34:26.704 EST [2882019] LOG:  checkpoint complete: wrote 26 buffers (0.2%); 0 WAL file(s) added, 0 removed, 33 recycled; write=18.568 s, sync=0.089 s, total=20.304 s; sync files=3, longest=0.066 s, average=0.030 s; distance=542018 kB, estimate=542018 kB; lsn=2/93120808, redo lsn=2/751E8920\n",
      "2025-01-06 17:34:26.717 EST [2882019] LOG:  checkpoints are occurring too frequently (20 seconds apart)\n",
      "2025-01-06 17:34:26.717 EST [2882019] HINT:  Consider increasing the configuration parameter \"max_wal_size\".\n",
      "2025-01-06 17:34:26.717 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:34:40.028 EST [2882019] LOG:  checkpoint complete: wrote 33 buffers (0.2%); 0 WAL file(s) added, 1 removed, 33 recycled; write=11.641 s, sync=0.022 s, total=13.311 s; sync files=2, longest=0.022 s, average=0.011 s; distance=559033 kB, estimate=559033 kB; lsn=2/B515EB80, redo lsn=2/973D6FC0\n",
      "2025-01-06 17:34:40.038 EST [2882019] LOG:  checkpoints are occurring too frequently (14 seconds apart)\n",
      "2025-01-06 17:34:40.038 EST [2882019] HINT:  Consider increasing the configuration parameter \"max_wal_size\".\n",
      "2025-01-06 17:34:40.038 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:35:00.834 EST [2882019] LOG:  checkpoint complete: wrote 22 buffers (0.1%); 0 WAL file(s) added, 0 removed, 33 recycled; write=19.252 s, sync=0.047 s, total=20.797 s; sync files=3, longest=0.018 s, average=0.016 s; distance=553086 kB, estimate=558438 kB; lsn=2/D6DF2018, redo lsn=2/B8FF6B98\n",
      "2025-01-06 17:35:01.072 EST [2882019] LOG:  checkpoints are occurring too frequently (21 seconds apart)\n",
      "2025-01-06 17:35:01.072 EST [2882019] HINT:  Consider increasing the configuration parameter \"max_wal_size\".\n",
      "2025-01-06 17:35:01.072 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:35:23.167 EST [2882019] LOG:  checkpoint complete: wrote 20 buffers (0.1%); 0 WAL file(s) added, 0 removed, 33 recycled; write=20.556 s, sync=0.058 s, total=22.095 s; sync files=3, longest=0.038 s, average=0.020 s; distance=527061 kB, estimate=555301 kB; lsn=2/F6F8E498, redo lsn=2/D92AC2C0\n",
      "2025-01-06 17:35:24.256 EST [2882019] LOG:  checkpoints are occurring too frequently (23 seconds apart)\n",
      "2025-01-06 17:35:24.256 EST [2882019] HINT:  Consider increasing the configuration parameter \"max_wal_size\".\n",
      "2025-01-06 17:35:24.256 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:35:53.987 EST [2882019] LOG:  checkpoint complete: wrote 22 buffers (0.1%); 0 WAL file(s) added, 0 removed, 33 recycled; write=28.070 s, sync=0.029 s, total=29.732 s; sync files=2, longest=0.016 s, average=0.015 s; distance=538527 kB, estimate=553623 kB; lsn=3/17CF8990, redo lsn=2/FA0942B8\n",
      "2025-01-06 17:35:55.824 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:36:24.445 EST [2882019] LOG:  checkpoint complete: wrote 27 buffers (0.2%); 0 WAL file(s) added, 0 removed, 33 recycled; write=26.972 s, sync=0.081 s, total=28.621 s; sync files=3, longest=0.071 s, average=0.027 s; distance=540696 kB, estimate=552331 kB; lsn=3/38DCFBB0, redo lsn=3/1B09A618\n",
      "2025-01-06 17:36:25.449 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:36:53.706 EST [2882019] LOG:  checkpoint complete: wrote 26 buffers (0.2%); 0 WAL file(s) added, 0 removed, 33 recycled; write=26.775 s, sync=0.024 s, total=28.257 s; sync files=2, longest=0.013 s, average=0.012 s; distance=541152 kB, estimate=551213 kB; lsn=3/59DC7D00, redo lsn=3/3C1127A0\n",
      "2025-01-06 17:36:55.097 EST [2882019] LOG:  checkpoint starting: wal\n",
      "2025-01-06 17:37:29.998 EST [2882019] LOG:  checkpoint complete: wrote 22 buffers (0.1%); 0 WAL file(s) added, 0 removed, 33 recycled; write=33.284 s, sync=0.095 s, total=34.902 s; sync files=3, longest=0.042 s, average=0.032 s; distance=543444 kB, estimate=550436 kB; lsn=3/7B06A8E8, redo lsn=3/5D3C7918\n",
      "2025-01-06 17:37:32.661 EST [2882019] LOG:  checkpoint starting: wal\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: \"pos\"\n",
      "CONTEXT:  COPY malin_gnomad, line 30209586, column pos: \"pos\"\n",
      "\n",
      "[SQL: COPY malin_gnomad\n",
      "FROM PROGRAM 'ls /home/mcn26/varef/data/Malinois/gnomAD_variants/gnomad.genomes.v3.1.2.sites.*.vcf.gz | grep -v \".converted.vcf.gz\" | xargs gzip -dc'\n",
      "DELIMITER E'\\t'\n",
      "HEADER;]\n",
      "(Background on this error at: https://sqlalche.me/e/20/9h9h)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-06 17:37:44.385 EST [2882192] ERROR:  invalid input syntax for type integer: \"pos\"\n",
      "2025-01-06 17:37:44.385 EST [2882192] CONTEXT:  COPY malin_gnomad, line 30209586, column pos: \"pos\"\n",
      "2025-01-06 17:37:44.385 EST [2882192] STATEMENT:  COPY malin_gnomad\n",
      "\tFROM PROGRAM 'ls /home/mcn26/varef/data/Malinois/gnomAD_variants/gnomad.genomes.v3.1.2.sites.*.vcf.gz | grep -v \".converted.vcf.gz\" | xargs gzip -dc'\n",
      "\tDELIMITER E'\\t'\n",
      "\tHEADER;\n",
      "xargs: gzip: terminated by signal 13\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "COPY malin_gnomad\n",
    "FROM PROGRAM 'ls /home/mcn26/varef/data/Malinois/gnomAD_variants/gnomad.genomes.v3.1.2.sites.*.vcf.gz | grep -v \".converted.vcf.gz\" | xargs -I {} sh -c \"gzip -dc {} | tail -n +2\"'\n",
    "DELIMITER E'\\t';"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4907c38-d465-447d-854d-88f5455caf01",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%sql\n",
    "ALTER TABLE malin_gnomad ALTER COLUMN info SET STORAGE EXTENDED;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5b6765dc-dde3-4ba8-826a-96fc39c1ce42",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-28T20:25:52.067855Z",
     "iopub.status.busy": "2025-01-28T20:25:52.067422Z",
     "iopub.status.idle": "2025-01-28T20:25:52.073174Z",
     "shell.execute_reply": "2025-01-28T20:25:52.072862Z",
     "shell.execute_reply.started": "2025-01-28T20:25:52.067837Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done :-)\n"
     ]
    }
   ],
   "source": [
    "print(\"Done :-) Stopping the server\",flush=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3a724632-8d24-44da-849e-9846794a0629",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-01-16T14:47:22.247770Z",
     "iopub.status.busy": "2025-01-16T14:47:22.247371Z",
     "iopub.status.idle": "2025-01-16T14:47:22.865472Z",
     "shell.execute_reply": "2025-01-16T14:47:22.864659Z",
     "shell.execute_reply.started": "2025-01-16T14:47:22.247741Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pg_ctl: PID file \"/home/mcn26/palmer_scratch/db/postmaster.pid\" does not exist\n",
      "Is server running?\n"
     ]
    }
   ],
   "source": [
    "#stop the sql db\n",
    "!pg_ctl -D ~/palmer_scratch/db stop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "34ae61dc-a999-4ccb-b3e5-a075cc9d5760",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"[+] Waiting 120s for the server to stop\",flush=True)\n",
    "time.sleep(120)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
